apiVersion: perses.dev/v1alpha1
kind: Perses
metadata:
  name: perses
  namespace: redhat-ods-monitoring
spec:
  metadata:
    labels:
      instance: perses
  config:
    database:
      file:
        folder: '/perses'
        extension: 'yaml'
    frontend:
      disable: false
    schemas:
      panels_path: '/etc/perses/cue/schemas/panels'
      queries_path: '/etc/perses/cue/schemas/queries'
      datasources_path: '/etc/perses/cue/schemas/datasources'
      variables_path: '/etc/perses/cue/schemas/variables'
    ephemeral_dashboard:
      enable: true
      cleanup_interval: '1s'
  image: registry.redhat.io/cluster-observability-operator/perses-0-50-rhel9:1.2.2-1752686994
  containerPort: 8080
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
