apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: redhat-ods-monitoring
spec:
  selector:
    app: lgtm
  ports:
    - name: otlp
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlphttp
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
